# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "bigchaindb"

[service]
name = "bigchaindb"
image = "quay.io/eris/bigchaindb"
environment = [ "BIGCHAIN_DATABASE_HOST=rethinkdb" ]

command = "bigchaindb start"

[dependencies]
services = [ "rethinkdb" ]

[maintainer]
name = "Zach Ramsay"
email = "zach@erisindustries.com"

[location]
