# Eris service definition for bitcoinclassic
# Start it with `$ eris services start bitcoinclassic`

# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name           = "bitcoinclassic"

[service]
image          = "quay.io/eris/bitcoinclassic"
data_container = true
ports          = [ "8333:8333", "8334:8334" ]
volumes        = [  ]
environment    = [  ]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/common/blob/master/docker/bitcoinclassic/Dockerfile"
