# eris service definition for bitcoinxt
name           = "bitcoinxt"

[service]
image          = "erisindustries/bitcoinxt"
data_container = true
ports          = [ "8333:8333", "8332:8332" ]
volumes        = [  ]
environment    = [  ]
cpu_shares     = 10

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/eris-services"

[machine]
include = [ "docker" ]
requires = [ "" ]
