# Eris service definition for btcd
# Start it with `$ eris services start btcd`

# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name           = "btcd"

[service]
image          = "quay.io/eris/btcd"
data_container = true
ports          = [ "8333:8333", "8334:8334" ]
volumes        = [  ]
environment    = [  ]
cpu_shares     = 10

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/common/blob/master/docker/btcd/Dockerfile"

[machine]
include = [ "docker" ]
requires = [ "" ]
