# eris service definition for btcd
[service]
name           = "btcd"
image          = "eris/btcd"
data_container = true
ports          = [ "8333:8333", "8334:8334", "8333:8333" ]
volumes        = [  ]
environment    = [  ]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/eris-services"

[machine]
include = [ "docker" ]
requires = [ "" ]
