# Eris service definition for compilers
# Start it with `$ eris services start compilers`

# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name           = "compilers"

[service]
image          = "quay.io/eris/compilers"
data_container = true
ports          = [ "9090:9098", "9091:9099" ]
volumes        = [  ]
environment    = [ "SECURE_PORT=9098", "UNSECURE_PORT=9099" ]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/common/blob/master/docker/compilers/Dockerfile"
