
# main readable config settings
[service]
image       = "eris/erisdb"
ports       = [ "46656:46656", "46657:46657" ]
environment = [ "TMROOT=/data/tendermint" ]

[manager]
start = "./start run"
fetch = "./start fetch"
new = "./start new"

[maintainer]
name  = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/eris-services"

[machine]
include  = [ "docker" ]
requires = [ "" ]
