[service]
name           = "erisdb"
image          = "eris/erisdb:develop"
ports          = [ "46656:46656", "46657:46657" ]
environment    = [ "TMROOT=/home/eris/.eris/blockchains/tendermint", "NODE_ADDR=http://pinkpenguin.chaintest.net:46657"]
data_container = true

[maintainer]
name  = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/eris-services"

[machine]
include  = [ "docker" ]
requires = [ "" ]
