# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "keys"
description = """
Eris' key signing daemon. Generate and manage keys for your application.

This service is usually linked to a chain and/or an application. Its functionality is wrapped by `eris keys`.
"""

status = "alpha"

[service]
image = "quay.io/eris/keys"
data_container = true
exec_host = "ERIS_KEYS_HOST"
restart = "always"

[location]
dockerfile = "https://github.com/eris-ltd/eris-keys/blob/master/Dockerfile"
#see also http://github.com/eris-ltd/common/blob/master/docker/keys/build.sh"
repository = "https://github.com/eris-ltd/eris-keys"
website = "https://docs.erisindustries.com/documentation/ekeys/"
