# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "logrotate"

[service]
name = "logrotate"
image = "tutum/logrotate"
data_container = false
volumes = [ "/var/lib/docker/containers:/var/lib/docker/containers:rw" ]

[dependencies]

[maintainer]
name = "Casey Kuhlman"
email = "casey@erisindustries.com"

[location]

[machine]
