# Eris service definition for logspout
# Start it with `$ eris services start logspout`

# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "logspout"

[service]
name = "logspout"
image = "gliderlabs/logspout"
data_container = false
entry_point = "/bin/logspout"
command = "syslog://logs2.papertrailapp.com:XXXXX" 
ports = [ "8000:8000" ]
volumes = [ "/var/run/docker.sock:/tmp/docker.sock" ]

[dependencies]

[maintainer]
name = "Casey Kuhlman"
email = "casey@erisindustries.com"

[location]
repository = "github.com/gliderlabs/logspout"

[machine]
