# Eris service definition for logsrotate
# Start it with `$ eris services start logsrotate`

# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "logrotate"

[service]
name = "logrotate"
image = "tutum/logrotate"
data_container = false
volumes = [ "/var/lib/docker/containers:/var/lib/docker/containers:rw" ]

[dependencies]

[maintainer]
name = "Casey Kuhlman"
email = "casey@erisindustries.com"

[location]
repository = "github.com/tutumcloud/logrotate"

[machine]
