
chain 	       = "$chain"

# eris service definition for mindy
[service]
name           = "mindy"
image          = "eris/mindy"

[services]
dependencies = ["tinydns"]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/mindy"

[machine]
include = [ "docker" ]
requires = [ "" ]
