# Eris service definition for mindy
# Start it with `$ eris services start mindy`

# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

chain 	       = "$chain:mint:l"

[service]
name           = "mindy"
image          = "eris/mindy"
environment    = [ "UPDATE_EVERY=5" ]

[dependencies]
services = ["tinydns::v"]

[maintainer]
name = "Ethan Buchman"
email = "ethan@erisindustries.com"

[location]
repository = "github.com/eris-ltd/mindy"

[machine]
include = [ "docker" ]
requires = [ "" ]
