
chain 	       = "$chain:mint:l"

# eris service definition for mindy
[service]
name           = "mindy"
image          = "eris/mindy"
environment    = [ "UPDATE_EVERY=5" ]

[services]
dependencies = ["tinydns::v"]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/mindy"

[machine]
include = [ "docker" ]
requires = [ "" ]
