[service]
name           = "mint"
image          = "eris/mint"
ports          = [ "46656:46656", "46657:46657" ]
environment    = [ "TMROOT=/home/eris/.eris/blockchains/tendermint" ]
data_container = true

[manager]
fetch = "tendermint node --fast_sync" # we'd like this to stop when caught up!
start = "tendermint node"
new   = "tendermint node && last_pid=$! && sleep(1) && kill -KILL $last_pid"

[maintainer]
name  = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/eris-services"

[machine]
include  = [ "docker" ]
requires = [ "" ]
