# eris service definition for tendermint
# main readable config settings
[service]
image       = "eris/mint"
ports       = [ "46656:46656", "46657:46657" ]
#volumes     = [ "$pwd:/tendermint_root" ]
environment = [ "TMROOT=/tendermint_root" ]

[maintainer]
name  = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/eris-services"

[machine]
include  = [ "docker" ]
requires = [ "" ]
