# eris service definition for tendermint
# main readable config settings
[service]
name        = "mintx"
image       = "eris/mint"
ports       = [ "46656", "46657" ]
environment = [ "TMROOT=/data/tendermint" ]

[manager]
fetch = "./build/tendermint node --fast_sync" # we'd like this to stop when caught up!
start = "./build/tendermint node"
new = "./build/tendermint node && last_pi=$! && sleep(1) && kill -KILL $last_pid"

[maintainer]
name  = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/eris-services"

[machine]
include  = [ "docker" ]
requires = [ "" ]
