# Eris service definition for openbazaar
# Start it with `$ eris services start openbazaar`

# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "openbazaar"

[service]
name = "openbazaar"
image = "quay.io/eris/openbazaar:latest"
data_container = true
#command = "/sbin/my_init"
host_name = "ob"
ports = ["8888:8888", "12345:12345"]
expose = ["9300"]
environment = [ "RUNSH_ARGS=--disable-upnp -q 8888 -p 12345" ]

#[dependencies]
#services = ["ob-elk"]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/common/blob/master/docker/openbazaar/build.sh"

[machine]
requires = ["docker"]
include = [""]
