# eris service definition for sandstorm
[service]
name           = "sandstorm"
image          = "erisindustries/sandstorm"
data_container = true
ports          = [ "6080:6080" ]
volumes        = [  ]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/eris-services"

[machine]
include = [ "docker" ]
requires = [ "" ]
