# eris service definition for tendermint
# main readable config settings
image = "eris/erisdb"
ports = [ "30303:30303", "50505:50505" ]
volumes = [  ]
environment = [  ]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/eris-services"

[machine]
include = [ "docker" ]
requires = ""
