# Eris service definition for tinydns
# Start it with `$ eris services start tinydns`

# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

[service]
name        = "tinydns"
image       = "quay.io/eris/tinydns"
ports       = [ "53/udp" ]
data_container = true

[maintainer]
name  = "Ethan Buchman"
email = "ethan@erisindustries.com"

[location]
repository = "github.com/eris-ltd/mindy/tree/master/tinydns"
