name = "toadserver"
chain = "$chain:toad:l"

# NOTE: this definition file is a WIP
# and requires modification to work properly
# please see README/tutorial in repo

# both MINT_CHAINID and MINTX_PUBKEY
# need to be hardcoded. see test.sh
# in repo for more info

[service]
name = "toadserver"
image = "quay.io/eris/toadserver"
ports = [ "11113:11113" ]
volumes = [  ]
environment = [  
	"MINTX_NODE_ADDR=http://toad:46657/",
	"MINTX_CHAINID=$CHAIN_NAME", 
	"MINTX_SIGN_ADDR=http://eris_service_keys_1:4767", 
	"MINTX_PUBKEY=$PUB_KEY",
	"ERIS_IPFS_HOST=http://ipfs"
]

[dependencies]
services = [ "ipfs", "keys" ]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/toadserver"

[machine]
include = [ "docker" ]
requires = [ "" ]
