# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml
name = "watchtower"

[service]
name = "watchtower"
image = "centurylink/watchtower"
data_container = false
volumes = [ "/var/run/docker.sock:/var/run/docker.sock" ]

[dependencies]

[maintainer]
name = "Casey Kuhlman"
email = "casey@erisindustries.com"

[location]

[machine]
