# Eris service definition for watchtower
# Start it with `$ eris services start watchtower`

# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "watchtower"

[service]
name = "watchtower"
image = "centurylink/watchtower"
data_container = false
volumes = [ "/var/run/docker.sock:/var/run/docker.sock" ]

[dependencies]

[maintainer]
name = "Casey Kuhlman"
email = "casey@erisindustries.com"

[location]
repository = "github.com/CenturyLinkLabs/watchtower"
